Import('env')
source_env = env.Clone()

if str(Platform()) == 'win32':
  source_env.Append(CPPDEFINES = [
    'XULRUNNER_SDK',
    'WIN32',
    '_DEBUG',
    '_WINDOWS',
    'XP_WIN32',
    'MOZILLA_STRICT_API',
    'XPCOM_GLUE',
    'XP_WIN',
    '_X86_',
    'setbackground_plugin_EXPORTS',
    '_CRT_SECURE_NO_WARNINGS',
    '_CRT_SECURE_NO_DEPRECATE'
    '_WINDLL',
    '_UNICODE',
    'UNICODE'
    ])
  source_env.Append(CPPFLAGS = ['/EHsc', '/MTd'])
  source_env.Append(LIBS = ['urlmon.lib', 'userenv.lib', 'user32.lib', 'ole32.lib', 'advapi32.lib'])
else:
  # Unsupported platform
  assert False

# Targets to build C++ files
sources = source_env.Object(source_env.Glob('*.cc'))

if str(Platform()) == 'win32':
  # Add the def file to the sources list in windows. SCons will figure out what
  # to do with it.
  sources = sources + [source_env.File('module_definition.def')]

# Target for plugin shared library
dll = source_env.SharedLibrary('setwallpaper_plugin', sources)

Return('dll')
